### ISSUE TITLE
Not really an issue just a way to get a hold of you.

### ISSUE THREAD

**Issue by DouglasAllen** [noahgibbs/best_quotes#2]
Hi Noah,
  Have you ever used sinatra-activerecord?
I was thinking that we could build, modify, or use this gem for some nifty migration work.
You put the requirement for it in your Rakefile and use your app configurations to link in the db.
No need to even write a single Rake task unless we're gonna rebuild 'er.
Have fun. tAKE Care.

**Comment by DouglasAllen** [comment]
P.S. I have an app that I started on but there's no models yet. It does use similar folder layout like Rails though. Any suggestions? See https://github.com/DouglasAllen/my_active_record_sinatra

**Comment by noahgibbs** [comment]
Fun! I hadn't used it. Looks a bit like Padrino's integration with ActiveRecord, but a bit smoother on the migrations.
