### ISSUE TITLE
private method `new' called for BestQuotes::Application:Class (NoMethodError)

### ISSUE THREAD

**Issue by mateusdeap** [noahgibbs/best_quotes#4]
I really tried searching google as to what this could possibly mean, but I could not figure it out. It started happening as soon as I inserted the changes in chapter 1 to my equivalent of rulers.rb (in my case, jets.rb) 

```
require "jets/version"

module Jets
  class Application
    def call(env)
      [200, {'Content-Type' => 'text/html'},
        ["Hello from Ruby on Jets!"]]
    end
  end
end
```

and also added the Application class to the BestQuotes module and tried to call .new on it

```
require './config/application'
run BestQuotes::Application.new
```

Has anybody come accross the same issue?

**Comment by noahgibbs** [comment]
Have a look at where you declare BestQuotes::Application. It should be a class inherited from Jets::Application. Is it possible you instead declared it as a Module, or in some other unexpected way?

**Comment by mateusdeap** [comment]
Well, I declared BestQuotes as a module and Application as a class that inherits Jets::Application, like so:

```
require "jets"

module BestQuotes
  class Application < Jets::Application
  end
end
```

**Comment by noahgibbs** [comment]
That looks perfectly reasonable. Can you check in your code somewhere, and I can download it and see if I can repro?

**Comment by mateusdeap** [comment]
Sure. I'll share it here on github as soon as I can and I'll send you the link. And thank you very much for your time! When I heard about your book I was pretty excited since it was exactly what I wanted ever since I started working with rails and started to feel the need to know how it ticked!

**Comment by mateusdeap** [comment]
Ok, so I think I actually found out what the problem was. I downloaded the two projects here at work and was testing them to see if I would have any luck.

It turns out that I couldn't even build the gem here. It kept saying that the gemspec was invalid and that the gem contained itself:

![image](https://user-images.githubusercontent.com/14188887/65982289-633df700-e451-11e9-8fb3-338bb81d5861.png)

I did some research and, apparently, the problem was that I had the .gem file in the root folder. So I deleted it and added to the .gitignore and tried to build again, which prompted a second error: 

![image](https://user-images.githubusercontent.com/14188887/65982323-7781f400-e451-11e9-8f4a-cd2b9a3fe613.png)

I did some more research and found out that I needed to commit the changes first because of the line in the .gemspec file where `git ls-files -z` is run. So I commited and did the build+install routine and finally the application worked.

![image](https://user-images.githubusercontent.com/14188887/65982442-c2037080-e451-11e9-9b27-e7f5ec1e5f18.png)

All that is left is to give it a try at home and I suspect it must have something to do with the fact that, at home, I use asdf to manage my ruby versions. Once I get home I'll investigate some more and post any findings here, in case more people run into this.

**Comment by noahgibbs** [comment]
Sounds good. I'm glad that it sounds like you've figured out your problem. If you reproduce this bug (or another one) and want another set of eyes on it, upload it and I'll have a look!

**Comment by mateusdeap** [comment]
So I figured it all out. The problem was that there is a gem named 'jets' in rubygems.org, and when I ran `bundle install` it would fetch that gem and not use my gem. Everything got solved once I added the `:path => "../jets"` to the Gemfile.

After that, in my case, at least, all I did was remove all the gems that had been installed by accident because of this other jets gem and run bundle install again, and everything was peachy.

What I don't understand is why I didn't have this problem at my work environment. I really do suspect that it has something to do with asdf vs. RVM. Anyways, it wasn't a bug or anything, just the wrong gem being installed and used by accident.

**Comment by noahgibbs** [comment]
It also may have to do with the instructions in the book - if you build locally with "gem build" and then install from the built gemfile with "gem install jets-0.0.1.gem" you'll always get the local gem... But "bundle install" with RubyGems.org as a listed source will pull the RubyGems one.

**Comment by noahgibbs** [comment]
Note that you can use a solution from a later chapter to fix this: if you use the :path option for the gem it will always look locally rather than from RubyGems for that specific gem.

**Comment by mateusdeap** [comment]
> It also may have to do with the instructions in the book - if you build locally with "gem build" and then install from the built gemfile with "gem install jets-0.0.1.gem" you'll always get the local gem... But "bundle install" with RubyGems.org as a listed source will pull the RubyGems one.

Yeah, precisely. I guess I was just in my work mode and instinctively ran bundle install because that's what I do for all rails projects. It's funny you should mention this because, as I read the book, I kept wondering why you never said to run bundle install. I don't know what was I thinking...

So I guess the takeaway is to not run bundle install in the application project. At least not in the first chapter. That, or use the :path option.

**Comment by noahgibbs** [comment]
A bit later (chapter 3, maybe?) I suggest using :path. But I should add a warning about bundle install!

(This kind of thing is part of why I'm so happy to get bug reports from readers. I often learn something!)

This sounds like we can probably close this issue. If you agree, feel free to do so. Or if you disagree, let me know what I can help with.

**Comment by mateusdeap** [comment]
Yup, fine by me. Closing it now. And, once again, awesome book!
